export type ProductSupabaseType = {
  brand: string;
  category: string;
  created_at: string;
  description: string;
  has_large_size: boolean;
  has_medium_size: boolean;
  has_small_size: boolean;
  has_xlarge_size: boolean;
  id: number;
  image_url0: string;
  image_url1: string;
  image_url2: string;
  image_url3: string;
  is_on_sale: boolean;
  large_quantity: number;
  medium_quantity: number;
  name: string;
  price: number;
  sale_discount: number;
  sale_price: number;
  small_quantity: number;
  total_quantity: number;
  type: string;
  xlarge_quantity: number;
};
