import { ProductType } from "./product";
import img from "@/app/assets/productImage.png";

export const productsData: ProductType[] = [
	{
		productID: 1,
		productName: "Product 1",
		productDescription: "Description of Product 1",
		isOnSale: true,
		productPrice: 50,
		productSalePrice: 40,
		productSaleDiscount: 20,
		hasSmallSize: true,
		hasMediumSize: true,
		hasLargeSize: true,
		hasXLargeSize: false,
		productSmallQuantity: 100,
		productMediumQuantity: 75,
		productLargeQuantity: 500,
		productXLargeQuantity: 0,
		productQuantity: 675,
		productCategory: "Category A",
		productBrand: "Brand A",
		productImageURL: img,
		productType: "tents",
	},
	{
		productID: 2,
		productName: "Product 2",
		productDescription: "Description of Product 2",
		isOnSale: false,
		productPrice: 30,
		productSalePrice: 0,
		productSaleDiscount: 0,
		hasSmallSize: true,
		hasMediumSize: false,
		hasLargeSize: true,
		hasXLargeSize: false,
		productSmallQuantity: 50,
		productMediumQuantity: 0,
		productLargeQuantity: 30,
		productXLargeQuantity: 0,
		productQuantity: 80,
		productCategory: "Category B",
		productBrand: "Brand B",
		productImageURL: img,
		productType: "tents",
	},
	{
		productID: 3,
		productName: "Product 3",
		productDescription: "Description of Product 3",
		isOnSale: true,
		productPrice: 100,
		productSalePrice: 10,
		productSaleDiscount: 90,
		hasSmallSize: true,
		hasMediumSize: true,
		hasLargeSize: true,
		hasXLargeSize: true,
		productSmallQuantity: 0,
		productMediumQuantity: 0,
		productLargeQuantity: 0,
		productXLargeQuantity: 0,
		productQuantity: 0,
		productCategory: "Category C",
		productBrand: "Brand C",
		productImageURL: img,
		productType: "tents",
	},
	// Continue the structure for the remaining 17 products
	// Ensure to change the values to create a diverse set of products.
];
